export const FETCHED_ORDERS = "FETCHED_ORDERS";
export const FETCH_CUSTOMER_ORDERS = "FETCH_CUSTOMER_ORDERS";
export const CREATE_ORDER = "CREATE_ORDER";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const RESET_ORDER = "RESET_ORDER";
