export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM_FROM_DATABASE = "DELETE_ITEM_FROM_DATABASE";
export const UPLOAD_PRODUCT_IMAGES = "UPLOAD_PRODUCT_IMAGES";
export const RESET_CART = "RESET_CART";
export const RESET_IMAGE_UPLOADS = "RESET_IMAGE_UPLOADS";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
